name: Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_BUILD_PATH: build
      PROJECT_INSTALL_PATH: ${{ github.event.repository.name }}-linux-x64

    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Prepare Environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev
          mkdir -p ${{ env.PROJECT_INSTALL_PATH }}
        shell: bash

      - name: Configure
        run: |
          cmake -B ${{ env.PROJECT_BUILD_PATH }} -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Build
        run: |
          cmake --build ${{ env.PROJECT_BUILD_PATH }}
        shell: bash

      - name: Generate Artifacts
        run: |
          ls -l ${{ env.PROJECT_BUILD_PATH }}/src
          cp ${{ env.PROJECT_BUILD_PATH }}/src/${{ env.PROJECT_NAME }} ${{ env.PROJECT_INSTALL_PATH }}/
          ls -l ${{ env.PROJECT_INSTALL_PATH }}
          7z a ./${{ env.PROJECT_INSTALL_PATH }}.zip ./${{ env.PROJECT_INSTALL_PATH }}
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_INSTALL_PATH }}.zip
          path: ./${{ env.PROJECT_INSTALL_PATH }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.PROJECT_INSTALL_PATH }}.zip
          generate_release_notes: true
          draft: true

  build-web:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_BUILD_PATH: build-web
      PROJECT_INSTALL_PATH: ${{ github.event.repository.name }}-web

    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.48
          actions-cache-folder: 'emsdk-cache'

      - name: Prepare Environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev
          mkdir -p ${{ env.PROJECT_INSTALL_PATH }}
        shell: bash

      - name: Configure
        run: |
          emcmake cmake -S . -B ${{ env.PROJECT_BUILD_PATH }} -DPLATFORM=Web -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Build
        run: |
          cmake --build ${{ env.PROJECT_BUILD_PATH }}
        shell: bash

      - name: Generate Artifacts
        run: |
          ls -l ${{ env.PROJECT_BUILD_PATH }}/src
          cp ${{ env.PROJECT_BUILD_PATH }}/src/${{ env.PROJECT_NAME }}.html ${{ env.PROJECT_INSTALL_PATH }}/index.html
          cp ${{ env.PROJECT_BUILD_PATH }}/src/${{ env.PROJECT_NAME }}.js ${{ env.PROJECT_INSTALL_PATH }}/
          cp ${{ env.PROJECT_BUILD_PATH }}/src/${{ env.PROJECT_NAME }}.wasm ${{ env.PROJECT_INSTALL_PATH }}/
          ls -l ${{ env.PROJECT_INSTALL_PATH }}
          7z a ./${{ env.PROJECT_INSTALL_PATH }}.zip ./${{ env.PROJECT_INSTALL_PATH }}
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_INSTALL_PATH }}.zip
          path: ./${{ env.PROJECT_INSTALL_PATH }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.PROJECT_INSTALL_PATH }}.zip
          generate_release_notes: true
          draft: true

  build-windows:
    runs-on: windows-latest

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_BUILD_PATH: build
      PROJECT_INSTALL_PATH: ${{ github.event.repository.name }}-windows-x64

    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Prepare Environment
        run: |
          mkdir -p ${{ env.PROJECT_INSTALL_PATH }}
        shell: bash

      - name: Configure
        run: |
          cmake -B ${{ env.PROJECT_BUILD_PATH }}
        shell: bash

      - name: Build
        run: |
          cmake --build ${{ env.PROJECT_BUILD_PATH }} --target ${{ env.PROJECT_NAME }} --config Release
        shell: bash

      - name: Generate Artifacts
        run: |
          ls -l ${{ env.PROJECT_BUILD_PATH }}/src
          cp ${{ env.PROJECT_BUILD_PATH }}/src/Release/${{ env.PROJECT_NAME }}.exe ${{ env.PROJECT_INSTALL_PATH }}/
          ls -l ${{ env.PROJECT_INSTALL_PATH }}
          7z a ./${{ env.PROJECT_INSTALL_PATH }}.zip ./${{ env.PROJECT_INSTALL_PATH }}
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_INSTALL_PATH }}.zip
          path: ./${{ env.PROJECT_INSTALL_PATH }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.PROJECT_INSTALL_PATH }}.zip
          generate_release_notes: true
          draft: true
